 http.all.authmanager=oerealm
 client.login.model=form
 OEClientPrincipalFilter.domain=spark
 OEClientPrincipalFilter.anonymous=true
 OEClientPrincipalFilter.sealAnonymous=true
 OEClientPrincipalFilter.forwardToken=true
 OESSO.error.detail=2
 OERealm.AuthProvider.multiTenant=true
 OERealm.AuthProvider.userDomain=spark
 OERealm.UserDetails.realmClass=Sports.Spark.Core.Security.SportsRealm
 OERealm.UserDetails.grantedAuthorities=ROLE_NoAccess
 OERealm.UserDetails.appendRealmError=true
 OERealm.UserDetails.realmTokenFile=SparkRealm.cp
